server:
  port: 8888

spring:
  application:
    name: turbine-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9988/eureka/
      turbine:
      # 要监控的微服务列表，多个用,分隔
      appConfig: index-service
      clusterNameExpression: "'default'"